# Generated by Django 3.2.12 on 2023-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAME',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
