# Generated by Django 3.2.12 on 2023-05-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_game_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user_count',
        ),
    ]
