# Generated by Django 3.2.12 on 2023-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
