# Generated by Django 3.2.12 on 2023-05-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_game_user_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GAME',
        ),
    ]
